/**
 * Long-scroll order (top → bottom). Section numbers match `SectionLabel` / ScrollProgress dots.
 */
export const SITE_DOCUMENT_ORDER = [
  "Hero (#hero)",
  "SectionBreak",
  "01 Pavilion premise — #pavilion-lead (PavilionLeadSection)",
  "SectionBreak",
  "The Paradigm Shift — #paradigm-shift (ParadigmShiftSection)",
  "SectionBreak",
  "02 Design Concept — #concept (DesignConcept)",
  "SectionBreak",
  "03 Design Process — #design-process (DesignProcess)",
  "ScrollProgress rail",
  "04 System — #system",
  "SectionBreak",
  "05 Material Exploration — #materials",
  "SectionBreak",
  "06 Prototyping — #prototyping",
  "SectionBreak",
  "07 Behavior — #behavior",
  "SectionBreak",
  "08 Walkthrough — #pavilion-walkthrough (PavilionSection)",
  "SectionBreak",
  "09 The Pavilion — #pavilion (PavilionReveal)",
  "SectionBreak",
  "10 Media / Archive — #archive (MediaArchive)",
  "SectionBreak",
  "Footer",
] as const;
